apiVersion: v1
entries:
  keda-kaito-scaler:
  - apiVersion: v2
    appVersion: v0.6.1
    created: "2026-07-16T12:52:50.420813628Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: c902cf5a90426a83b742ba18f20e570c5029e27c68535f5eb4bb7adfc615c574
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: v0.6.0
    created: "2026-07-14T09:15:29.386653991Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 22a8fc0ec3c7f55b785d43f40fd6304248b10553655aa7dafdeaa54c40d3c1f1
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: v0.5.1
    created: "2026-05-11T09:53:44.322877607Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: b4e9e79ed057a3ddb90dab874e479f95ca71a99e74fe48fa7df32752edb69697
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: v0.5.0
    created: "2026-05-05T04:19:39.455943233Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 8d17d5d972f244215f5cff3a136f8a599b95b7bd53d78ae51077397f0a273844
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: v0.4.1
    created: "2026-04-27T13:54:26.282785139Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 95b851de3c781ea926df60413b74b57e70920dd0ea8098a4db0a3439a6af3107
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: v0.4.0
    created: "2026-04-23T05:05:26.322910783Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: d39497b73db7e98c4697b73d4cd95c0933b6981ce57bfcbd92e18ebea0bf1d10
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: v0.3.3
    created: "2025-11-24T07:35:04.755306027Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 2bd6c847c1455a7ae379c6e4ce03211a6b171f6ba3ad6fe4624666bbc2cec1ed
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    appVersion: v0.3.0
    created: "2025-11-24T05:34:04.604727614Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 80a131f9c996199b4bb447f52ec1110d5850747a76209ebb2832ffe174a425ec
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2025-11-07T07:09:57.06807353Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: ea5e3df12527485265bbac66af851a3931fdd1f4543843e4ba349bfdaa9abc85
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v0.0.1
    created: "2025-08-29T07:25:49.178791572Z"
    description: A Helm chart for Kaito keda-kaito-scaler component.
    digest: 0dd856beaa286718276ad3f860cd1e5a55850f6df90e0c3a753a9cd5ed532af1
    name: keda-kaito-scaler
    type: application
    urls:
    - https://kaito-project.github.io/keda-kaito-scaler/charts/kaito-project/keda-kaito-scaler-0.0.1.tgz
    version: 0.0.1
generated: "2026-07-16T12:52:50.420339337Z"
