apiVersion: v1
kind: Secret
metadata:
  name: keda-kaito-scaler-webhook-certs
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keda-kaito-scaler-certs
  namespace: {{ .Release.Namespace }}
  type: kubernetes.io/tls
  data:
    ca.crt: ""
    tls.crt: ""
    tls.key: ""
    server.crt: ""
    server.key: ""